# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shreyas Kumar Singh
title: Data Scientist
email: sk.shreyassingh@gmail.com
mobile: +61 480 244 892
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: sin_shreyas
github_username:  ShreyasSingh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sin_shreyas
linkedin_username: sinshreyas
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a recent graduate with a Master of Data Science and Master of Research from Macquarie University, Sydney. I am skilled in exploratory data analysis, statistical modeling, machine learning, data visualization and sound mathematical and reasoning skills. Proficient in Python, R, SQL, and various data analysis tools.  Seeking to leverage my skills and experience to contribute to the growth of a forward-thinking organization.


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MACQUARIE UNIVERSITY, Sydney, NSW
        caption: Jan 2022 - Dec 2022 (Expected)
        sub_title: Master of Research
        quote: >
          Improving Retrieval System for QA System
        description: | # this will include new lines to allow paragraphs
          My Research is focused on building a retrieval system (Search)  to be used for a QA System.

      - layout: left
        title: MACQUARIE UNIVERSITY, Sydney, NSW
        caption: Feb 2020 - Dec 2021
        sub_title: Master of Data Science
        sub_title: WAM - 80 (Distinction) 
        quote: >

        description: | # this will include new lines to allow paragraphs
          Secured High distinction in Machine Learning and Big Data

 
      - layout: left
        title: UNIVERSITY OF MUMBAI, Mumbai, MH, India
        caption: July 2012 - Aug 2016
        sub_title: Bachelor of Engineering 
        quote: >

        description: | # this will include new lines to allow paragraphs
          Major in Computer engineering

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Macquarie University
        link: mq.edu.au
        # link_text: boringcompany.com
        sub_title: Sessional Teaching Academic
        caption: January 2022 - Present
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Responsibilities:
            - Involved in conducting Workshops and Practicals for groups of 20 to 30 students in each class
            - Taught Fundamentals of Computer Science using Python, Big Data and Machine Learning to Undergrad and Postgrad students
            - Conducted one-to-one consultation classes
            - Graded students assignments 
            - Conducted Viva for final exam assessment

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
